/* 大專校院選單資料（僅名稱分類，不含校安／諮商聯絡資訊） */
var UNIVERSITY_LIST = [
  /* 北部 · 公立 */
  { id: 'sch_ntu', name: '國立臺灣大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntnu', name: '國立臺灣師範大學', region: 'north', ownership: 'public' },
  { id: 'sch_nccu', name: '國立政治大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntou', name: '國立臺灣海洋大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntpu', name: '國立臺北大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntust', name: '國立臺灣科技大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntut', name: '國立臺北科技大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntue', name: '國立臺北教育大學', region: 'north', ownership: 'public' },
  { id: 'sch_tnua', name: '國立臺北藝術大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntua', name: '國立臺灣藝術大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntub', name: '國立臺北商業大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntunhs', name: '國立臺北護理健康大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntcpa', name: '國立臺灣戲曲學院', region: 'north', ownership: 'public' },
  { id: 'sch_utaipei', name: '臺北市立大學', region: 'north', ownership: 'public' },
  { id: 'sch_nou', name: '國立空中大學', region: 'north', ownership: 'public' },
  { id: 'sch_nycu', name: '國立陽明交通大學', region: 'north', ownership: 'public' },
  { id: 'sch_nthu', name: '國立清華大學', region: 'north', ownership: 'public' },
  { id: 'sch_ncu', name: '國立中央大學', region: 'north', ownership: 'public' },
  { id: 'sch_ntsu', name: '國立體育大學', region: 'north', ownership: 'public' },
  { id: 'sch_nuu', name: '國立聯合大學', region: 'north', ownership: 'public' },
  /* 北部 · 私立 */
  { id: 'sch_fju', name: '輔仁大學', region: 'north', ownership: 'private' },
  { id: 'sch_tku', name: '淡江大學', region: 'north', ownership: 'private' },
  { id: 'sch_scu', name: '東吳大學', region: 'north', ownership: 'private' },
  { id: 'sch_pccu', name: '中國文化大學', region: 'north', ownership: 'private' },
  { id: 'sch_shu', name: '世新大學', region: 'north', ownership: 'private' },
  { id: 'sch_mcu', name: '銘傳大學', region: 'north', ownership: 'private' },
  { id: 'sch_usc', name: '實踐大學', region: 'north', ownership: 'private' },
  { id: 'sch_ttu', name: '大同大學', region: 'north', ownership: 'private' },
  { id: 'sch_tmu', name: '臺北醫學大學', region: 'north', ownership: 'private' },
  { id: 'sch_au', name: '真理大學', region: 'north', ownership: 'private' },
  { id: 'sch_mcuhs', name: '馬偕醫學院', region: 'north', ownership: 'private' },
  { id: 'sch_dila', name: '法鼓文理學院', region: 'north', ownership: 'private' },
  { id: 'sch_lhu', name: '龍華科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_mcut', name: '明志科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_sju', name: '聖約翰科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_jwu', name: '景文科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_tnut', name: '東南科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_tmit', name: '德明財經科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_cute', name: '中國科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_hsc', name: '醒吾科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_chihlee', name: '致理科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_ayit', name: '亞東科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_hust', name: '華夏科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_tct', name: '臺北城市科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_cmu', name: '中華海洋科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_lit', name: '黎明技術學院', region: 'north', ownership: 'private' },
  { id: 'sch_mkc', name: '馬偕醫護管理專科學校', region: 'north', ownership: 'private' },
  { id: 'sch_knu', name: '康寧大學', region: 'north', ownership: 'private' },
  { id: 'sch_cycu', name: '中原大學', region: 'north', ownership: 'private' },
  { id: 'sch_yzu', name: '元智大學', region: 'north', ownership: 'private' },
  { id: 'sch_cgu', name: '長庚大學', region: 'north', ownership: 'private' },
  { id: 'sch_knuo', name: '開南大學', region: 'north', ownership: 'private' },
  { id: 'sch_chihlee2', name: '健行科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_vnu', name: '萬能科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_cgust', name: '長庚科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_chu', name: '中華大學', region: 'north', ownership: 'private' },
  { id: 'sch_hw', name: '玄奘大學', region: 'north', ownership: 'private' },
  { id: 'sch_ypu', name: '元培醫事科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_mit', name: '明新科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_ydu', name: '育達科技大學', region: 'north', ownership: 'private' },
  { id: 'sch_jente', name: '仁德醫護管理專科學校', region: 'north', ownership: 'private' },
  /* 中部 · 公立 */
  { id: 'sch_nchu', name: '國立中興大學', region: 'central', ownership: 'public' },
  { id: 'sch_nutn', name: '國立臺中科技大學', region: 'central', ownership: 'public' },
  { id: 'sch_ncut', name: '國立勤益科技大學', region: 'central', ownership: 'public' },
  { id: 'sch_ntcu', name: '國立臺中教育大學', region: 'central', ownership: 'public' },
  { id: 'sch_ntuspe', name: '國立臺灣體育運動大學', region: 'central', ownership: 'public' },
  { id: 'sch_nou_tc', name: '國立空中大學（臺中學習指導中心）', region: 'central', ownership: 'public' },
  { id: 'sch_ncue', name: '國立彰化師範大學', region: 'central', ownership: 'public' },
  { id: 'sch_ncnu', name: '國立暨南國際大學', region: 'central', ownership: 'public' },
  { id: 'sch_yuntech', name: '國立雲林科技大學', region: 'central', ownership: 'public' },
  { id: 'sch_nfu', name: '國立虎尾科技大學', region: 'central', ownership: 'public' },
  /* 中部 · 私立 */
  { id: 'sch_fcu', name: '逢甲大學', region: 'central', ownership: 'private' },
  { id: 'sch_thu', name: '東海大學', region: 'central', ownership: 'private' },
  { id: 'sch_cmu2', name: '中國醫藥大學', region: 'central', ownership: 'private' },
  { id: 'sch_au2', name: '亞洲大學', region: 'central', ownership: 'private' },
  { id: 'sch_pu', name: '靜宜大學', region: 'central', ownership: 'private' },
  { id: 'sch_csmu', name: '中山醫學大學', region: 'central', ownership: 'private' },
  { id: 'sch_cyut', name: '朝陽科技大學', region: 'central', ownership: 'private' },
  { id: 'sch_hust2', name: '弘光科技大學', region: 'central', ownership: 'private' },
  { id: 'sch_ltu', name: '嶺東科技大學', region: 'central', ownership: 'private' },
  { id: 'sch_ctust', name: '中臺科技大學', region: 'central', ownership: 'private' },
  { id: 'sch_ocu', name: '僑光科技大學', region: 'central', ownership: 'private' },
  { id: 'sch_hcuet', name: '臺中市修平科技大學', region: 'central', ownership: 'private' },
  { id: 'sch_dyu', name: '大葉大學', region: 'central', ownership: 'private' },
  { id: 'sch_ctu', name: '建國科技大學', region: 'central', ownership: 'private' },
  { id: 'sch_mdu', name: '明道大學', region: 'central', ownership: 'private' },
  { id: 'sch_ghu', name: '環球科技大學', region: 'central', ownership: 'private' },
  { id: 'sch_nkut', name: '南開科技大學', region: 'central', ownership: 'private' },
  /* 南部 · 公立 */
  { id: 'sch_ccu', name: '國立中正大學', region: 'south', ownership: 'public' },
  { id: 'sch_ncyu', name: '國立嘉義大學', region: 'south', ownership: 'public' },
  { id: 'sch_ncku', name: '國立成功大學', region: 'south', ownership: 'public' },
  { id: 'sch_ntun', name: '國立臺南大學', region: 'south', ownership: 'public' },
  { id: 'sch_tnnua', name: '國立臺南藝術大學', region: 'south', ownership: 'public' },
  { id: 'sch_nou_tn', name: '國立空中大學（臺南學習指導中心）', region: 'south', ownership: 'public' },
  { id: 'sch_nsysu', name: '國立中山大學', region: 'south', ownership: 'public' },
  { id: 'sch_nuk', name: '國立高雄大學', region: 'south', ownership: 'public' },
  { id: 'sch_nkust', name: '國立高雄科技大學', region: 'south', ownership: 'public' },
  { id: 'sch_nknu', name: '國立高雄師範大學', region: 'south', ownership: 'public' },
  { id: 'sch_nkuht', name: '國立高雄餐旅大學', region: 'south', ownership: 'public' },
  { id: 'sch_npust', name: '國立屏東科技大學', region: 'south', ownership: 'public' },
  { id: 'sch_nptu', name: '國立屏東大學', region: 'south', ownership: 'public' },
  { id: 'sch_afats', name: '空軍軍官學校', region: 'south', ownership: 'public' },
  { id: 'sch_na', name: '海軍軍官學校', region: 'south', ownership: 'public' },
  { id: 'sch_ccc', name: '陸軍軍官學校', region: 'south', ownership: 'public' },
  { id: 'sch_nou_kh', name: '國立空中大學', region: 'south', ownership: 'public' },
  { id: 'sch_knou', name: '高雄市立空中大學', region: 'south', ownership: 'public' },
  /* 南部 · 私立 */
  { id: 'sch_nhu', name: '南華大學', region: 'south', ownership: 'private' },
  { id: 'sch_wfu', name: '吳鳳科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_cjcu', name: '長榮大學', region: 'south', ownership: 'private' },
  { id: 'sch_stust', name: '南臺科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_ksu', name: '崑山科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_cnu', name: '嘉南藥理大學', region: 'south', ownership: 'private' },
  { id: 'sch_tainan', name: '台南應用科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_cmu3', name: '中華醫事科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_feu', name: '遠東科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_tnu', name: '台灣首府大學', region: 'south', ownership: 'private' },
  { id: 'sch_must', name: '敏實科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_cjrm', name: '崇仁醫護管理專科學校', region: 'south', ownership: 'private' },
  { id: 'sch_kmu', name: '高雄醫學大學', region: 'south', ownership: 'private' },
  { id: 'sch_isu', name: '義守大學', region: 'south', ownership: 'private' },
  { id: 'sch_stu', name: '樹德科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_wzu', name: '文藻外語大學', region: 'south', ownership: 'private' },
  { id: 'sch_pu2', name: '輔英科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_csu', name: '正修科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_kyu', name: '高苑科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_tf', name: '東方設計大學', region: 'south', ownership: 'private' },
  { id: 'sch_yuhing', name: '育英醫護管理專科學校', region: 'south', ownership: 'private' },
  { id: 'sch_meiho', name: '美和科技大學', region: 'south', ownership: 'private' },
  { id: 'sch_tzuhui', name: '慈惠醫護管理專科學校', region: 'south', ownership: 'private' },
  /* 東部 · 公立 */
  { id: 'sch_niu', name: '國立宜蘭大學', region: 'east', ownership: 'public' },
  { id: 'sch_ndhu', name: '國立東華大學', region: 'east', ownership: 'public' },
  { id: 'sch_nttu', name: '國立臺東大學', region: 'east', ownership: 'public' },
  { id: 'sch_nou_e', name: '國立空中大學（宜蘭、花蓮、臺東學習指導中心）', region: 'east', ownership: 'public' },
  /* 東部 · 私立 */
  { id: 'sch_fgu', name: '佛光大學', region: 'east', ownership: 'private' },
  { id: 'sch_tku_ly', name: '淡江大學（蘭陽校區）', region: 'east', ownership: 'private' },
  { id: 'sch_tzu', name: '慈濟大學', region: 'east', ownership: 'private' },
  { id: 'sch_smm', name: '聖母醫護管理專科學校', region: 'east', ownership: 'private' },
  { id: 'sch_ctcn', name: '耕莘健康管理專科學校（宜蘭校區）', region: 'east', ownership: 'private' },
  { id: 'sch_tcu', name: '慈濟科技大學', region: 'east', ownership: 'private' }
];

var UNIVERSITY_REGIONS = [
  { id: 'north', label: '北部' },
  { id: 'central', label: '中部' },
  { id: 'south', label: '南部' },
  { id: 'east', label: '東部' }
];

var UNIVERSITY_OWNERSHIP = [
  { id: 'public', label: '公立大專校院' },
  { id: 'private', label: '私立大專校院' }
];
